---

- hosts: borgbackup
  become: yes
  gather_facts: yes
  roles:
          - role: collect_ssh_keys
            #the user for backup jobs running, should be the same as backup_client_user
            ssh_user: "root"


- hosts: secondbackup.rascom.ru
  become: yes
  gather_facts: yes
  roles:
          - role: authorize_ssh_keys
            ssh_keys: "{{ groups['borgbackup'] | map('extract', hostvars, ['ssh_public_key']) | list }}"
            #the user for communicate with backup server, should be the same as backup_server_user
            ssh_user: "borg"
            ssh_key_options: 'command="borg serve --restrict-to-path /borg/repos",no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc'


- hosts: borgbackup
  become: yes
  gather_facts: yes

  roles:
          #- role: add_epel

          #- setup_basic_mta

          - role: setup_borg_client
            backup_client_user: "root"
            backup_server: "secondbackup.rascom.ru"
            backup_server_user: "borg"
            backup_repos_path: "/borg/repos"
            #backup_repository: "general_repo"          # define if you want one repo for hosts
            backup_emailto: "mshubin@rascom.ru"         # notify recipient
            backup_emailfrom: "noreply@rascom.ru"       # from address
            remove_crontab_jobs: false                  # remove all borg jobs before adding new
            backup_server_key: "secondbackup.rascom.ru ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvx26cRFnp51Za1yMOnGPFJ5R7eO1t5ibe77wRMYYkdXXNsKdprkTIOX3GIw5dRLVfhxWHvAbG6/ve1WV/HTrcgwA1fQgiIQHqrurOqImIhUuMxQrk/SdyZM1XYHOp1KmjZVaiXH/NdXGuuSo0XJZMfnWMcQCjypT+a7Bd4RGN2eB2wtp/LcF0/MGLy07juzwQx9f+gVuk6Pm+L7J3R1zx0Y7ieqEpQXkrgDnkVdItISW7uUtMnXQsAqQRFSLloNT58TYlkErjMI2if13+G/saTcUnkoxrnujLxqoqCfL2qC46O7mMnplB0MDzkPWcsXYy9EHEFaYHN8Cv1nYjDpkH"


